#:schema node_modules/wrangler/config-schema.json
name = "shinedigitalstore-1"
main = "functions/api.js"
compatibility_date = "2024-01-01"

# Website Assets များအတွက် folder သတ်မှတ်ခြင်း
[site]
bucket = "."

[[d1_databases]]
binding = "DB"
database_name = "shine-d"
database_id = "43309224-37d7-4497-a24e-376133db3bb3"

[[r2_buckets]]
binding = "SHINE_MEDIA"
bucket_name = "shine-media"
