#:schema node_modules/wrangler/config-schema.json
name = "shinedigitalstore-1"
main = "functions/api.js"
compatibility_date = "2024-01-01"

# 1️⃣ D1 Database ချိတ်ဆက်မှု (ID အစစ်အမှန်ဖြင့်)
[[d1_databases]]
binding = "DB"
database_name = "shine-d"
database_id = "43309224-37d7-4997-a24e-376133db3bb3"

# 2️⃣ R2 Storage Bucket ချိတ်ဆက်မှု
[[r2_buckets]]
binding = "SHINE_MEDIA"
bucket_name = "shine-media"
